Controllers films users
AndreyMeltsov/java-filmorate pull request #2
Opened 2023-01-29 11:37 UTC by AndreyMeltsov

Первая проверка

2023-01-29 17:58 UTC, kalitva requested changes

2023-01-29 17:58 UTC, kalitva commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Форматируй пробелами вместо табов

2023-01-29 17:58 UTC, kalitva commented on pom.xml
> +	<description>Сервис, который будет работать с фильмами и оценками пользователей</description>
Описание по английски

2023-01-29 17:58 UTC, kalitva commented on pom.xml
> +		<relativePath/> <!-- lookup parent from repository -->
Удали коммент

2023-01-29 17:58 UTC, kalitva commented on pom.xml
> +		</dependency>
В большинстве случаях спринг-бут управляет версиями зависимостей, лучше не переопределять

```
   <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>
```

2023-01-29 17:58 UTC, kalitva commented on pom.xml
> +		</dependency>
gson удали

2023-01-29 17:58 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +
Форматируй пробелами

2023-01-29 17:58 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FutureFromSpecifiedDateValidator.java
> +        return value.isAfter(LocalDate.of(1895, 12, 28));
Вынеси дату в константу

2023-01-29 17:58 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Фильма с таким id не существует");
Описание ошибки в исключениях - по английски

2023-01-29 17:58 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank
Лучше отделять пустыми линиями поля с аннотациями, легче читается если много полей

2023-01-29 17:58 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FutureFromSpecifiedDate.java
> +public @interface FutureFromSpecifiedDate {
Я бы еще подумал над названием, specified date - не очень информативно

2023-01-30 05:45 UTC, AndreyMeltsov commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Похоже он так был сгенерирован. У меня в идее не видно, что там - пробелы или табы, Но при автоформатировании почти весь файл форматнулся, вроде как заменились...

2023-01-30 05:48 UTC, AndreyMeltsov commented on pom.xml
> +	<description>Сервис, который будет работать с фильмами и оценками пользователей</description>
done

2023-01-30 05:49 UTC, AndreyMeltsov commented on pom.xml
> +		<relativePath/> <!-- lookup parent from repository -->
done

2023-01-30 06:02 UTC, AndreyMeltsov commented on pom.xml
> +		</dependency>
done

2023-01-30 06:03 UTC, AndreyMeltsov commented on pom.xml
> +		</dependency>
done

2023-01-30 06:06 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +
done

2023-01-30 06:12 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FutureFromSpecifiedDateValidator.java
> +        return value.isAfter(LocalDate.of(1895, 12, 28));
done

2023-01-30 06:15 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Фильма с таким id не существует");
done

2023-01-30 06:17 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank
done

2023-01-30 06:21 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FutureFromSpecifiedDate.java
> +public @interface FutureFromSpecifiedDate {
done

2023-01-30 07:21 UTC, kalitva approved these changes

2023-01-30 07:21 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +package ru.yandex.practicum.filmorate;
Давай удалим тот файл

2023-01-30 07:21 UTC, kalitva commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Да, файл так генерится, сейчас окей.

В git diff видно, советую вообще всегда смотреть git diff перед коммитом, не только из-за пробелов

2023-01-30 07:21 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FutureFromCinemaBirthday.java
> +    String message() default "{FutureFromCinemaBirthday.invalid}";
Здесь лучше подробнее описать ошибку, что-то типа "Дата релиза не может быть раньше такого-то числа"

2023-01-30 07:21 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FutureFromCinemaBirthday.java
> +    Class<?>[] groups() default { };
Если без этих полей валидация работает, лучше их убрать

2023-01-31 02:19 UTC, AndreyMeltsov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +package ru.yandex.practicum.filmorate;
done

2023-01-31 02:27 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FutureFromCinemaBirthday.java
> +    String message() default "{FutureFromCinemaBirthday.invalid}";
done

2023-01-31 02:28 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FutureFromCinemaBirthday.java
> +    Class<?>[] groups() default { };
Нет без них валидация в Postman не проходит.

2023-01-31 02:31 UTC, merged