feat: Добавили друзей и лайки
AndreyMeltsov/java-filmorate pull request #3
Opened 2023-02-12 05:21 UTC by AndreyMeltsov

Добавили друзей и лайки

2023-02-12 16:44 UTC, kalitva requested changes

2023-02-12 16:44 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
Во всех обработчиках обязательно нужно залогировать исключение

https://www.baeldung.com/slf4j-log-exceptions

2023-02-12 16:44 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmStorage filmStorage;
Стораджей не должно быть в контроллере, нужно обращаться только к сервисам, а сервисы делегируют вызов стораджам. Удали поле стораджа

2023-02-12 16:44 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService;
private final

2023-02-12 16:44 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted((x1, x2) -> x2.getLikesIds().size() - x1.getLikesIds().size())
Обычно компаратор примерно так реализуется

`.sorted(Comparator.comparing(f -> f.getLikesIds().size()))`

2023-02-12 16:44 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +package ru.yandex.practicum.filmorate.storage.film;
Предлагаю не разбивать дополнительно на пакеты по сущностям, это не добавит много удобства в данном случае, хотя и допустимо. Лучше положить все в один пакет, дибо так сделать - создай в `storage` пакет `impl` и положи туда реализации интерфейсов, в самом же пакете оставь интерфейсы

2023-02-12 16:44 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  }
То же, что и для `FilmController`

2023-02-13 09:42 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
done

2023-02-13 10:04 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmStorage filmStorage;
done

2023-02-13 10:04 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService;
done

2023-02-13 10:18 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted((x1, x2) -> x2.getLikesIds().size() - x1.getLikesIds().size())
У меня обратный порядок сортировки, поэтому твое выражение не получается...

2023-02-13 10:32 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +package ru.yandex.practicum.filmorate.storage.film;
done

2023-02-13 10:32 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  }
done

2023-02-13 15:02 UTC, kalitva approved these changes

2023-02-13 15:02 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    private static final String LOG_MESSAGE = "An exception occurred";
Такое сообщение ни о чем не говорит, так что смысла в нем особого нет. В сообщении лучше написать тип ошибки (например `"bad request: " + e.getMessage()"` для метода ниже)

2023-02-13 15:02 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.error(LOG_MESSAGE, new ValidationException(e.getMessage()));
Вторым параметром нужно передать именно то исключение, которое пришло как аргумент
`log.error("bad request : " + e.getMessage(), e);`
Иначе потеряется стэктрэйс, а нам нужно чтобы он был залогирован

https://stackoverflow.com/questions/3988788/what-is-a-stack-trace-and-how-can-i-use-it-to-debug-my-application-errors

2023-02-13 15:02 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
Существует встроенный механизм отметить коммент как выполненный - под ним должна быть галочка, что-то типа "resolve conversation" это удобнее, коммент свернется и не будет мешать (обычно это ревьюер делает, но у меня прав нет)

2023-02-13 15:02 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public static class ErrorResponse {
private

2023-02-13 15:02 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted((x1, x2) -> x2.getLikesIds().size() - x1.getLikesIds().size())
Да точно. Можно так еще, вроде должно работать (но уже не выглядит сильно проще, просто на заметку)

`.sorted(Comparator.comparing(f -> f.getLikesIds().size(), Comparator.reverseOrder()))`

2023-02-14 09:35 UTC, merged