Add database
AndreyMeltsov/java-filmorate pull request #5
Opened 2023-03-11 05:17 UTC by AndreyMeltsov

2023-03-12 16:19 UTC, kalitva requested changes

2023-03-12 16:19 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film.Genre> findAllGenres() {
Сделай для `Genre` отдельный контроллер

2023-03-12 16:19 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static class Mpa {
Вынеси эти классы в файлы, все-таки они представляют собой сущности, и используются независимо от `Film`

2023-03-12 16:19 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>                  .collect(Collectors.toList());
Теперь эту выборку лучше делать на стороне базы. Можно удалить реализации ин-мемори стораджей и поправить интерфейсы по необходимости

2023-03-12 16:19 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                jdbcTemplate.update(sqlForGenreLine, filmId, genre.getId());
Используй `JdbdTemplate#batchUpdate` вместо перебора в цикле, будет лучше с точки зрения производительности

2023-03-12 16:19 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        } catch (DataAccessException e) {
`DataAccessException --> EmptyResultDataAccessException`

2023-03-12 16:19 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/exception/GenreNotFoundException.java
> +public class GenreNotFoundException extends RuntimeException {
Не думаю, что есть необходимость создавать not found исключение для каждой сущности, вполне хватит одного `NotFoundException`. Название сущности можно указать при выбрасывании исключения

2023-03-12 16:19 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        if (jdbcTemplate.update(sqlQuery, filmId, userId) > 0) {
Побочные эффекты в условных выражения - не очень хорошая практика, тем более запрос к БД. Сохрани результат вызова `update` в переменную, затем уже используй его в блоке if

2023-03-12 16:19 UTC, kalitva commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS ratings;
А эти дропы точно нужны? Как вижу, все таблицы создаются с `IF NOT EXISTS`...

2023-03-12 16:19 UTC, kalitva commented on src/main/resources/schema.sql
> +    name varchar(100)   NOT NULL,
Типы полей - тоже в upper case

2023-03-12 16:19 UTC, kalitva commented on src/main/resources/schema.sql
> +    --id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Пожалуйста, не оставляй закомментированный код

2023-03-12 16:19 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        Film.Mpa mpa = findRatingById(rs.getInt("rating_id"));
Фильм достается вместе с `Mpa` **одним** запросом, для этого нужно использовать `JOIN`: (запрос примерный)

```
SELECT * FROM films f
JOIN mpa m ON f.mpa_id = f.id
WHERE f.id = ?
```
Затем чтобы доставать поля из результ-сета, нужно будет указать имя таблицы через точку, например `        String name = rs.getString("films.name");`

2023-03-13 05:20 UTC, AndreyMeltsov commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS ratings;
Да, без них падают тесты

2023-03-13 19:42 UTC, kalitva requested changes

2023-03-13 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  @RestControllerAdvice(basePackages = "ru.yandex.practicum.filmorate.controller")
`basePackage` необязательно указывать, сомневаюсь, что это хоть на миллисекунду ускорит запуск приложения. Но можешь, конечно, оставить, если хочешь

2023-03-13 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.error(LOG_MESSAGE + e.getMessage());
1. А почему убрал `e`? Это же главная информация об ошибке
2. Сообщение "Bad request : " подходит там, где возвращается 4xx, для 500 никак не подходит. Статус 500  говорит о внутренней ошибке сервера

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

2023-03-13 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(String name,
Не понимаю необходимости в этом, на мой взгляд, такие конструкторы больше засоряют и запутывают код

2023-03-13 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        log.debug("Films quantity is: {}", films.size());
Все логирование перемести из стораджей в сервисы

2023-03-13 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        String sqlQuery = "SELECT * FROM films f JOIN ratings r ON f.rating_id = r.id WHERE f.id = ?";
Где-то запросы в lower case, где-то в смешанном. Не важно какой стиль выбран, но очень желательно чтобы был только один - либо тот, либо другой

2023-03-13 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        Long id = rs.getLong("films.id");
Два почти одинаковых метода не очень хорошо. Что если использовать перегрузку как полагается?

`return makeFilm(rs, rs.getLong("films.id"))`

Попробуй

2023-03-13 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +        if (user.getName() == null || user.getName().isBlank()) {
А вот эта штука должна быть в сервисе, не в сторадже

2023-03-13 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Соответственно, и это тоже

2023-03-13 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +                "(SELECT friend_id FROM user_friends AS b WHERE b.user_id = ?))";
А вместо второго сабселекта не получится джойн использовать?

2023-03-13 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +                .map(this::findUserById)
Вот так очень плохо в цикле или в стриме делать запросы по одной сущности, нужно джойнить

```
SELECT * FROM user_friends uf
JOIN users u ON u.id = uf.friend_id
WHERE status = 'CONFIRMED' AND user_id = ?
```

2023-03-13 19:42 UTC, kalitva commented on db/filmorate.trace.db
> +2023-03-04 14:47:51 jdbc[3]: exception
Нужно файлы БД удалить из репозитория и затем добавить `db/` в .gitignore`

2023-03-13 19:42 UTC, kalitva commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS ratings;
Видимо потому что данные БД коммитятся в репозиторий, в репе долны быть только исходники

2023-03-14 01:52 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.error(LOG_MESSAGE + e.getMessage());
1. потому что очень неудобно читать журнал логов при тестировании Postman'ом из длинных полотенец StackTrace'ов. 
2. Потому что в ТЗ-10 было сказано для ошибки валидации использовать код ответа 400. Могу вовсе убрать это исключение, сейчас оно у меня вроде нигде не используется...

2023-03-14 09:32 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +                .map(this::findUserById)
сделал но без проверки статуса, т.к. у меня он нигде не подтверждается, а при добавлении друга ставится requested

2023-03-15 00:48 UTC, AndreyMeltsov commented on db/filmorate.trace.db
> +2023-03-04 14:47:51 jdbc[3]: exception
сделал, но локально тесты postman'ом все равно валятся так как без drop'ов остается мусор в БД. Дропы оставил

2023-03-15 15:33 UTC, kalitva approved these changes

2023-03-15 15:33 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.error(LOG_MESSAGE + e.getMessage());
1. Окей
2. По кодам все правильно, имел ввиду, что сообщение `"Bad request : "` не подходит в обработчике, где возвращается код 500 (при логировании передается)

2023-03-15 15:33 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                log.debug("Friends quantity is: {}", friends.size());
Отступ съехал

2023-03-15 15:33 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    private final GenreStorage genreStorage;
Не помню, было ли это в прошлом ревью, возможно не заметил - классы хранилищ **нельзя** вайрить в друг друга. Можно и нужно вайрить в друг друга сервисы или в сервис несколько хранилищ

2023-03-15 15:33 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        userStorage.findUserById(userId);
Если нужно провалидировать, что по данному айди хранится пользователь, нужно делать это в сервисе

2023-03-15 15:33 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +        Long id = rs.getLong("id");
`return makeUser(rs,  rs.getLong("id"));`

2023-03-15 15:39 UTC, kalitva commented on db/filmorate.trace.db
> +2023-03-04 14:47:51 jdbc[3]: exception
1. Это неправильно, что приложение при запуске чистит БД. В данном случае следует зайти в БД и исполнить эти дропы вручную (ну или в случае h2 просто удалить файлы БД)
2. Вижу, что папка `db` по прежнему в репозитории, она здесь быть не должна

2023-03-19 23:50 UTC, merged